create table if not exists member
(
    member_id  bigint generated by default as identity primary key,
    account    varchar(255) unique,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    deleted_at timestamp,
    email      varchar(255),
    is_deleted boolean default false,
    name       varchar(255),
    password   varchar(255)
    );

create table if not exists board
(
    board_id    bigint generated by default as identity primary key,
    created_at  timestamp default CURRENT_TIMESTAMP not null,
    deleted_at  timestamp,
    description text,
    is_deleted  boolean default false,
    title       varchar(255),
    updated_at  timestamp,
    member_id   bigint references member (member_id)
    );

create table if not exists comment
(
    comment_id  bigint generated by default as identity primary key,
    created_at  timestamp default CURRENT_TIMESTAMP not null,
    deleted_at  timestamp,
    updated_at  timestamp,
    description text,
    is_deleted  boolean default false,
    board_id    bigint references board (board_id),
    member_id   bigint references member (member_id)
    );

